// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchryUAu4DLwiczz3TfHpImCvrnx_DVUM',
    appId: '1:730742556440:web:c9813ccc48f0d22374406d',
    messagingSenderId: '730742556440',
    projectId: 'college-app-95a70',
    authDomain: 'college-app-95a70.firebaseapp.com',
    storageBucket: 'college-app-95a70.firebasestorage.app',
    measurementId: 'G-LLWPTZZY9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcTkgHiG9cip5ZaYLInXd0VSS7ImwrfbM',
    appId: '1:730742556440:android:8ded2bed4030a6e574406d',
    messagingSenderId: '730742556440',
    projectId: 'college-app-95a70',
    storageBucket: 'college-app-95a70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6VPmtkLU94DVtzJj1xToQzjJzy7blWj8',
    appId: '1:730742556440:ios:528ab996f1e12fdc74406d',
    messagingSenderId: '730742556440',
    projectId: 'college-app-95a70',
    storageBucket: 'college-app-95a70.firebasestorage.app',
    iosBundleId: 'com.example.collegeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6VPmtkLU94DVtzJj1xToQzjJzy7blWj8',
    appId: '1:730742556440:ios:528ab996f1e12fdc74406d',
    messagingSenderId: '730742556440',
    projectId: 'college-app-95a70',
    storageBucket: 'college-app-95a70.firebasestorage.app',
    iosBundleId: 'com.example.collegeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAchryUAu4DLwiczz3TfHpImCvrnx_DVUM',
    appId: '1:730742556440:web:540d97164202d72874406d',
    messagingSenderId: '730742556440',
    projectId: 'college-app-95a70',
    authDomain: 'college-app-95a70.firebaseapp.com',
    storageBucket: 'college-app-95a70.firebasestorage.app',
    measurementId: 'G-MENQK3PL65',
  );
}
